### ISSUE TITLE
Cant get json_encode array to get the input names

### ISSUE THREAD

**Issue by Ramsz** [virtuagym/Virtuagym-Public-API#1]
Last couple of days I've managed to get the API to communicate with my enrollment form. 
**I'm so close** to finalizing the integration. Only one vital piece seems to fail.

I just cannot seem to link the HTML ´name´ attibutes of each each input field to get sent through the API. 

My question basically is: why does this work:

>     $fname = "John"; 
>     $lname = "Doe";
>     $email = "hi@mail.com"; 

But doesnt this work:

>     $fname = $_GET['roepnaam']; 
>     $lname = $_GET['last_name'];
>     $email = $_GET['e-mail'];

The names inside the brackets are the names in the HTML field names. 
Example:

`<tr class="even">
<td>
<label class="description">Voornaam *</label>
</td>
<td>
<INPUT TYPE="text" NAME="roepnaam" SIZE="20" MAXLENGTH="30">
</td>
</tr>
<tr class="odd">
<td>
<label class="description">Achternaam *</label>
</td>
<td>
<INPUT TYPE="text" NAME="last_name" SIZE="20" MAXLENGTH="30">
</td>
</tr>`

Complete API (fake keys etc) as shown below.

    <?php

    define('API_URL', 'https://virtuagym.com/api/v1/'); 
    define('API_KEY', 'MzuwtwgsAEXhNglVc0I7zVUWju1INauUwiV62XXX1rt'); 
    define('CLUB_ID', '12521'); 
    define('CLUB_KEY', 'CS-12521-ACCESS-7ilUAlrEiNC8PbGCylUVf0uXX'); 
 
    $fname = $_GET['roepnaam']; 
    $lname = $_GET['last_name']; 
    $mail= $_GET['e-mail']; 

    $customer_data = array( 
        "firstname" => $fname, 
        "lastname" => $lname, 
        "email" => $mail,
    ); 

    $data_string = json_encode($customer_data); 
     
    $url = API_URL.'club/'.CLUB_ID.'/member?api_key='.API_KEY.'&club_secret='.CLUB_KEY; 
    $ch = curl_init($url); 
    curl_setopt_array($ch, array( 
            CURLOPT_CUSTOMREQUEST => 'PUT', 
            CURLOPT_POSTFIELDS => $data_string, 
            CURLOPT_RETURNTRANSFER => true, 
            CURLOPT_SSL_VERIFYPEER => false // not the best way, but it works (might want to validate the certificate) 
        ) 
    ); 
    $result = curl_exec($ch); 
    curl_close($ch); 
     
    $response = json_decode($result); 
     
    echo 'Response: <br /><br />'; 
    echo '<pre>'; 
    var_dump($response); 
    echo '</pre>'; 

    get_footer(); ?>

What am I missing? Thank you!

**Comment by mark-hoeve** [comment]
How do you submit the form? Can you provide me with the whole form?

**Comment by Ramsz** [comment]
Thanks! The form can be seen here: http://pastebin.com/0cA2WEe6
The file that the form action links to is "aanmeldscript_mama.php". Not sure if this is problematic, its an old script. This script triggers a thank you mail after the form gets sent (not mandatory, if it breaks things).
The entire form action code can be seen here:  http://pastebin.com/i7j0T4Hs

Thanks!

**Comment by mark-hoeve** [comment]
Are you able to do a `var_dump` of `$_GET` once you submit the form? The example you gave should work if it's in the `aanmeldscript_mama.php`.

**Comment by Ramsz** [comment]
THANKS! You helped me a bunch! Moving the API to the 'aanmeldscript_mama.php.' file did the trick! 

One last issue though, the 'thank you' page that the user gets sent to (Aanmelding_mama_templateforbrowser_vak.php) has a personal touch.

We include their name, the course they registered for, and their email address like so: 

`<h2>Hoi [roepnaam], </h2>
                             Bedankt voor je inschrijving voor de [Cursus].<br>
							<h2> Vanwege de zomervakantie duurt het wat langer dan gebruikelijk voordat je je bevestiging en factuur via [e-mail] krijgt. Vanaf half augustus werken we weer op volle kracht. <br></h2>
							De inschrijvingen worden uiteraard op volgorde van binnenkomst verwerkt. <br>
							Fijne zomer.<br><br>
                             <br>	`

Unfortunatly the shortcuts are broken now and just show up as:

` [roepnaam]`,  `[Cursus]` and `[e-mail] `

Any chance in getting this to work correctly again? Or does the use of the API prohibit such functionality? 

Or does Virtuagym have its own 'thank you' page we could refer to?
Merci!

**Comment by Ramsz** [comment]
Nevermind! Solved it by replacing all POST with GET actions. Cheers and thanks for the support!

**Comment by mark-hoeve** [comment]
Awesome! Good luck :-)
