### ISSUE TITLE
Fetch timetable with API

### ISSUE THREAD

**Issue by Robgithup** [virtuagym/Virtuagym-Public-API#10]
Hi,

Is it possible to fetch the timetable ('Rooster' in dutch). If so, which request do I need?

Thx.

Rob

**Comment by roelvogel** [comment]
Hi Rob,
Sorry for the late reply, but you should have a look at this documentation: https://github.com/virtuagym/Virtuagym-Public-API/wiki/Club-Events. If you have any more questions, please let us know.

**Comment by wouterpotters** [comment]
I'm trying to do the same, but this request does require a _club secret_ that is nowhere to be found for individual end users of the API. Where can we obtain the _club secret_ required for the v1 api?

**Comment by retorquere** [comment]
Same here -- I'm a club member, and I'd like to integrate my booked classes in my calendar (a.o.)

**Comment by annuh** [comment]
I'd like to know this too. Would this be possible for club members?

**Comment by Pablo4VG** [comment]
Hi, I am sorry for the late reply, for future inquiries you can also use support@virtuagym.com to guarantee one of our Client Success representatives help you guide your doubt across our teams.

For accesing the "Club Key" / "club_secret" log in as the Club manager into the virtuagym portal and find it in System Settings→ Business info → Advanced
