### ISSUE TITLE
Retrieve member photo urls

### ISSUE THREAD

**Issue by djahermsen** [virtuagym/Virtuagym-Public-API#15]
I provide my trainers with custom dashboards about members. It would be great if we could show photos of members.

**Comment by Pablo4VG** [comment]
Hi, I am sorry for the late reply, for future inquiries you can also use support@virtuagym.com to guarantee one of our Client Success representatives help you guide your doubt across our teams.

We will consider this as feedback for future versions of the Club Member API, which does not allow this use case yet.
