### ISSUE TITLE
Issue with Club Events

### ISSUE THREAD

**Issue by khbeck** [virtuagym/Virtuagym-Public-API#16]
Good afternoon,

I’m loading club event and employee data from v1 API for reporting purposes. There are multiple instructors with unique member id ( appears to be the instructor ID, please confirm? ) in the JSON file from the Employees endpoint. However, when I pull the full Club Event history JSON file, only 2 unique instructor_id's are present, values 0 and another ID. 

 I 'm expecting at a minimum, 5 unique instructor ID's. Sync from date was set to club inception. 

Interesting enough, accessing and exporting the data through virtuagym.zendesk.com calendar provides a calendar of club events with the accurate instructor assigned.
 
Would you look into this issue and let me know if a fix is available?
Club ID: 14356

Warm regards,
KB

**Comment by yoramdelangen** [comment]
The instructor id is connected to a user instead of a member. After I figured it out it was pretty straight forward.
