### ISSUE TITLE
How to assign membership to the members

### ISSUE THREAD

**Issue by choijun** [virtuagym/Virtuagym-Public-API#18]
Hi there,
As well as my title of question - Could you show me how to assign membership to the members ?
I can't see it on the Wiki pages

Thank you.

**Comment by Pablo4VG** [comment]
Hi, I am sorry for the late reply, for future inquiries you can also use support@virtuagym.com to guarantee one of our Client Success representatives help you guide your doubt across our teams.

At the moment it is not a used case we contemplate on our public APIs, but we will value this as feedback for future versions

**Comment by agonzalezsc** [comment]
Hi,
Is there any news regarding a possible implementation of this feature?
