### ISSUE TITLE
How can i create a new user using API?

### ISSUE THREAD

**Issue by yogeshpatel2200** [virtuagym/Virtuagym-Public-API#2]
Hello,

How can i create new user using api?

**Comment by richarddigifit** [comment]
Hello, what you are looking for is explained at 
https://github.com/virtuagym/Virtuagym-Public-API/wiki/User

more specifically : a PUT on /api/v0/user

**Comment by yogeshpatel2200** [comment]
I already read this document, but problem is the response, it always show me 404, 
{
  "statuscode": 401,
  "statusmessage": "Missing or invalid API Key.",
  "result_count": 0,
  "timestamp": 1481831738
}

i already pass api_key, can you give me once example,  hoy to pass api_key?

**Comment by richarddigifit** [comment]
Have you already requested an API key?
if so, you can just use it by including the api_key=yourkey parameter in your API request.
for example /api/v0/user?api_key=abcdefgh

**Comment by yogeshpatel2200** [comment]
OK Thank you.

**Comment by yogeshpatel2200** [comment]
Hello when i create member using your below api it always give me 420 in response code, please help.

Here is below my code:

$data = array(
		  "firstname" => $first_name,
		  "lastname" => $last_name,
		  "email" => $username,
		  "is_pro" => true,
		  "send_invite_email" => true
		);
$url= "https://www.virtuagym.com/api/v0/club/".$club_id."/member?api_key=".$api_key."&club_secret=".$club_secret;

$ch = curl_init($url);
	  curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: text/plain'));
	  curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PUT");  
	  curl_setopt($ch, CURLOPT_POSTFIELDS,json_encode($data) );
	  curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
	  curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1); 
	  $result = curl_exec($ch);

**Comment by mark-hoeve** [comment]
I think you missed setting $club_id is this the whole code?

**Comment by yogeshpatel2200** [comment]
I done it, thanks!
