### ISSUE TITLE
How to assign a trainer to a club member

### ISSUE THREAD

**Issue by Evoolo** [virtuagym/Virtuagym-Public-API#20]
Hi all,

is there a way to add a Trainer to a Club-Member?

**Comment by Pablo4VG** [comment]
Hi, I am sorry for the late reply, for future inquiries you can also use support@virtuagym.com to guarantee one of our Client Success representatives help you guide your doubt across our teams.

At the moment it is not a used case we contemplate on our public APIs, but we will value this as feedback for future versions
