### ISSUE TITLE
Recurring booking conflict with credits 

### ISSUE THREAD

**Issue by meantraining** [virtuagym/Virtuagym-Public-API#21]
As any good schedule should have Virtuagym offers the ability to assign memberships to members and also offers the feature of recurring bookings. 

What I have found is due to the credit settings under each membership it is impossible to both limit the number of credits used per week, and, book multiple weeks in advance. 

The system will only renew credits week by week, therefore, will not allow enough credits available to book a number of weeks in advance on a recurring basis. 

The message is - not enough credits to book 

The solution offered was to set the minimum credits required to book to 0, which subsequently threw the entire schedule open to everyone and allowed clients without the appropriate membership to book into any session they wished as often as possible. 

I've been working with customer service for about a month now and we've been unable to come up with a solution. 

It seems the way credits are assigned and refreshed, simply conflicts with the way the system attempts to manage recurring bookings. 

Am I missing something? 

Or does the system need an update?

**Comment by Pablo4VG** [comment]
Hi, I am sorry for the late reply, for these kind of inquiries you can use support@virtuagym.com again to guarantee one of our Client Success representatives move your feedback across our dev teams.

At the moment it is the setting ""bookable in advance" what works in combination with the recurring bookings and credit features to achieve your use case, but we will consider this as feedback for future developments.
