### ISSUE TITLE
Is there a way to add leads to my gym?

### ISSUE THREAD

**Issue by bmuscolino** [virtuagym/Virtuagym-Public-API#24]
Hi there, 

I would live to add leads from various social media campaigns. Can I do that?

An xls import from the main page would work too. 

thanks,

**Comment by 7oh4nn** [comment]
> Hi there,
> 
> I would live to add leads from various social media campaigns. Can I do that?
> 
> An xls import from the main page would work too.
> 
> thanks,

Hi @bmuscolino ,

did you find any solution?
I'm struggling to solve the same issue.

thank you.

**Comment by stragyg** [comment]
I'm interested in this aswell.

We whould like to connect our social media marketing / website leads to VirtuaGym.

Thanks.

**Comment by Pablo4VG** [comment]
Hi, I am sorry for the late reply, for future inquiries you can also use support@virtuagym.com to guarantee one of our Client Success representatives help you guide your doubt across our teams.

At the moment this is work in progress and will be part of our public APIs soon, we will keep you posted via Virtuagym newsletters
