### ISSUE TITLE
Getting an access token

### ISSUE THREAD

**Issue by WDI-Json** [virtuagym/Virtuagym-Public-API#25]
I've tried multiple ways to get myself an access token. I'm using the public api to extract my own data for visualisation and making a demo before using the Club token. 

I have worked with API's before but still quite the noob. Could anyone help me sort this out so I can get started?

https://virtuagym.com/oauth/authorize?client_id=<API NAME>&response_type=code&state=<SETSTATE>
<img width="1026" alt="Screenshot 2020-02-07 at 08 17 32" src="https://user-images.githubusercontent.com/30670162/74008894-5e9ac980-4982-11ea-9b20-2e9ae62d6b61.png">

**Comment by steliyanag** [comment]
Which API are you trying to access?

**Comment by roelvogel** [comment]
Hello, it seems you haven't created a client yet, please create on here https://virtuagym.com/oauth/clients and make sure you are logged in with your virtuagym account. Then follow the steps you find under Oauth 2 here: https://github.com/virtuagym/Virtuagym-Public-API/wiki/Authorization. Hope this helps!

**Comment by WDI-Json** [comment]
Hey Roel, 

Thanks for your response! I thought I already created a client. I just edited the urls safety purposes 8-). 

see picture one: 
<img width="934" alt="Screenshot 2020-03-03 at 10 48 42" src="https://user-images.githubusercontent.com/30670162/75763550-b687de80-5d3c-11ea-92e8-e4a14a851702.png">

after this i used step 2 of your guide and used my id and give a state with it:
https://virtuagym.com/oauth/authorize?client_id=WouterAPItest&response_type=code&state=statetest123

it seems to work because I now have to give permission: 
<img width="795" alt="Screenshot 2020-03-03 at 10 53 14" src="https://user-images.githubusercontent.com/30670162/75763879-44fc6000-5d3d-11ea-8670-bf9d2c6e7bab.png">

When I do it ends up with the screenshot I posted... :(

**Comment by roelvogel** [comment]
Hi Wouter,

You should change your redirect url to a website you have control over so you can retrieve the access token, or at least change it to anything else that is not a virtuagym login page. The page you have entered now "https://tabonon.virtuagym.com/" is a virtuagym login page which handles oauth requests because oauth is used for Virtuagym Facebook log-in. That's why you are redirected to an error page of facebook.

Hope this helps!
