### ISSUE TITLE
Getting last-online/last_booking data

### ISSUE THREAD

**Issue by TijmenKop** [virtuagym/Virtuagym-Public-API#26]
In virtuagym you can see when a cliënt has been online for the last time, can i access this data through an Api?

**Comment by Pablo4VG** [comment]
Hi, I am sorry for the late reply, for future inquiries you can also use support@virtuagym.com to guarantee one of our Client Success representatives help you guide your doubt across our teams.

At the moment it is not a used case we contemplate on our public APIs, but we will value this as feedback for future versions
