### ISSUE TITLE
Problem while exchanging the authorization code for an access token

### ISSUE THREAD

**Issue by Jaimesuarezfer** [virtuagym/Virtuagym-Public-API#28]
Hi,

I am getting this error while trying to get the access token:
{
    "error": "invalid_request",
    "error_description": "The grant type was not specified in the request"
}
Does anyone know what am I missing?

Regards

**Comment by gceka25** [comment]
@Jaimesuarezfer the documentation is updated with a solution to this issue, please try again :)
