### ISSUE TITLE
Trigger Invitiation

### ISSUE THREAD

**Issue by Thulana** [virtuagym/Virtuagym-Public-API#29]
Hi,

Is there a way to trigger an invitation via the API by providing the Email maybe?

**Comment by Pablo4VG** [comment]
Hi Thulana, we recently updated the documentation to solve the doubt of how to make sure the invitation email is sent. To be more specific, this invitation is triggered when the member is created, so it could not be triggered after member creation via API.

You can find more context on [https://github.com/virtuagym/Virtuagym-Public-API/issues/32](https://github.com/virtuagym/Virtuagym-Public-API/issues/32) and [https://github.com/virtuagym/Virtuagym-Public-API/wiki/Club-Members](https://github.com/virtuagym/Virtuagym-Public-API/wiki/Club-Members)
