### ISSUE TITLE
How can I delete Member (Deprecated) ?

### ISSUE THREAD

**Issue by yogeshpatel2200** [virtuagym/Virtuagym-Public-API#3]
Hello can you,

Please suggest how can i delete Member(Deprecated)?

**Comment by mark-hoeve** [comment]
This is not possible in the v0 api, please refer to https://github.com/virtuagym/Virtuagym-Public-API/wiki/Club-Members for the v1 version with more options :-)

**Comment by yogeshpatel2200** [comment]
I already check this document, but i did't find any API method to delete club member. Please suggest me.
