### ISSUE TITLE
Automate weekly group session bookings

### ISSUE THREAD

**Issue by anoukkieboom** [virtuagym/Virtuagym-Public-API#30]
As gym member I would really love to automate my weekly group session bookings! Is this possible? Members of the Gym can add actions/activities, but I didn't find a way (yet) to subscribe to group sessions of the gym.

**Comment by pattersongp** [comment]
Were you able to figure this out? I would like to do the same.

I'm stuck on finding the `club_secret` it seems that once you have that, then you're able to use their v1 api

**Comment by sanjay900** [comment]
Try `/api/v0/club/{club}/event/{from}/to/{to}&api_key={api_key}`

Where from is an iso8601 date and to is an iso8601 date, both without times
e.g. `/api/v0/club/00000/event/2022-01-24/to/2022-01-25&api_key=xxxx`

As far as i can tell, the v0 API is for us to use, and the v1 API is for clubs to use.

Its also possible to book events via the v0 API too, 
```/api/v0/club/{club}/event/{event_id}/join&api_key={api_key}```

**Comment by gceka25** [comment]
@pattersongp Please note, in API endpoints we pass the "Club Key" as "club_secret"

(Club Key can be found in System Settings -> Business Info -> Advanced)
