### ISSUE TITLE
Invitation email is not being sent

### ISSUE THREAD

**Issue by jlubeck** [virtuagym/Virtuagym-Public-API#32]
Looking at the documentation here: https://github.com/virtuagym/Virtuagym-Public-API/wiki/Club-Members#put-example

It says:
```
When using this request to create a new member, they will automatically get e-mail invites based upon the club setting.
```

But I'm not getting any emails after creating new members... If I go into the portal and click on the link to send the invitation, then I get it.

Is there a setting somewhere that would be preventing the automatic email from being sent?

**Comment by jlubeck** [comment]
Ok, this was sorted by Customer Support. Looks like the setting to enable this is buried and hard to find:

`The option is located in System Settings→ Coach → Module Settings`

It works once that is enabled

**Comment by Pablo4VG** [comment]
Thanks for the follow up, I've updated the documentation accordingly.
