### ISSUE TITLE
Redirect after login is missing client_id

### ISSUE THREAD

**Issue by delaet** [virtuagym/Virtuagym-Public-API#33]
When I use the oauth flow and the user is not loggedin I need to press login first. When Iogin is done I get redirected to the oauth/authorize url. But the client_id is not in the url anymore.

`{"error":"invalid_client","error_description":"No client id supplied"}`

Am I missing something during this flow?

**Comment by gceka25** [comment]
@delaet are you following this guide: https://github.com/virtuagym/Virtuagym-Public-API/wiki/Authorization#1-create-an-oauth-client-configuration if so, than you should be logged in to the virtuagym account before continuing with the other steps in the oauth flow.
