### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by keesvanbemmel** [virtuagym/Virtuagym-Public-API#34]
Hi,

I feel rather stupid, but I can't seem to find in the documentation how paging / pagination works.

I'm listing all my food instances:
https://api.virtuagym.com/api/v0/food

This returns 500 results, but this is not all. How do I set the per page results (is there a maximum) and how to fetch the next page?

**Comment by richard1505** [comment]
you can use the url parameters max_results & page
for example
https://api.virtuagym.com/api/v0/food?max_results=50&page=2

**Comment by keesvanbemmel** [comment]
Thanks, and would you also happen to know how I can get access to my meals
and food items?

**Comment by gceka25** [comment]
@keesvanbemmel this can help you find your food plan: https://github.com/virtuagym/Virtuagym-Public-API/wiki/Food-Plan

**Comment by vgpaulo** [comment]
@keesvanbemmel we don't offer an endpoint for your own meals/products unfortunately
