### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by parrishtroyoffer** [virtuagym/Virtuagym-Public-API#35]
Is there any way to be able to send a push notification globally and to individual users? 
there doesn't seem to be any way even in the portal to send a custom push notification.

I would prefer to be able to do it from the API

**Comment by vgpaulo** [comment]
@parrishtroyoffer thanks for your question. Adding an API for push notifications is something that is on our radar. I can't tell you exactly when it will be available though.
