### ISSUE TITLE
`club_secret` for members

### ISSUE THREAD

**Issue by pattersongp** [virtuagym/Virtuagym-Public-API#36]
Hi, I'm a member at a gym that uses your service. How can I find the club secret? I don't have the business settings that are described in the docs, or at least I cannot find them.

**Comment by yoramdelangen** [comment]
Only owners/creators of the gym specific app can access/has that secret. That is what I have found out.

**Comment by pattersongp** [comment]
@yoramdelangen As far as I understood from the Wiki page, it should be available to the "general public"

> All v1 API's are open to the general public and requires both club_secret and api_key as query parameters for authorization.

**Comment by yoramdelangen** [comment]
> All v1 API's are open to the general public
What you want is part of v2 and that requires a club_secret. 

Although if the `club_secret` was public I would not be very happy because everyone could see my private information (known to the gym).

**Comment by markh07** [comment]
Club Secret is only available for club managers since it allows access to private information.
