### ISSUE TITLE
How can i delete Club Member Using Club Members API? 

### ISSUE THREAD

**Issue by yogeshpatel2200** [virtuagym/Virtuagym-Public-API#4]
I want to delete club member using Club member API, please suggest me how can i delete it.

**Comment by nathan-virtuagym** [comment]
Hi Yogesh,
We do not allow directly deleting a member but there is a field 'inactive' that can be passed in the PUT request that will mark the member as not being active anymore in the club.

https://github.com/virtuagym/Virtuagym-Public-API/wiki/Club-Members#put-example

**Comment by yogeshpatel2200** [comment]
The problem is i have, create once web application.
When any user purchase subscription in my website that time i create user in virtuagym as well as, but if user not purchase subscription next month and i made them to 'inactive' then this is ok?

**Comment by nathan-virtuagym** [comment]
Hi @yogeshpatel2200,
Yes, that should be fine - if your client does indeed buy a subscription at a later date all you would have to do is reset the 'inactive' field and the member would again be active. It is for this same reason we do not allow for completely deleting a member through the API yet.
