### ISSUE TITLE
Creating Club Event Participants as Guests

### ISSUE THREAD

**Issue by bsumter** [virtuagym/Virtuagym-Public-API#40]
I'd like to add participants to an event as **guests**. This means I don't want to create a member account for them.
I know OneFit is doing this, so it should be possible, but it's missing from the documentation.

**Comment by danielvdigifit** [comment]
Hey @bsumter the guest booking API is not publicly available but if you're interested in the possibilities you can freely reach out to kayleigh@digifit.eu to know more about our integrations.
