### ISSUE TITLE
Activity timestamp property does not contain correct time

### ISSUE THREAD

**Issue by nick-van-h** [virtuagym/Virtuagym-Public-API#41]
The returned timestamp of activities only contains the correct date part, however the time of day for all activities is 12:00 despite the activities themselves have different starting times.

**Example**
In my schedule I registered to a training from a club (occurs on 25-1-2022 18:30), however the returned object for that event contains the following
`
{"result":[
    {
     "timestamp":1643108400
    }
}
`
Which translates to 25-1-2022 12:00:00

**Comment by vgpaulo** [comment]
@nick-van-h better late than never, the answer for this is quite simple. We deliberately did this to prevent summer/wintertime issues and the time of the activity is not important. Hope that clears it up :)
