### ISSUE TITLE
Feature request: Retrieve club events as member without club secret

### ISSUE THREAD

**Issue by nick-van-h** [virtuagym/Virtuagym-Public-API#42]
For members it would be very useful to retrieve the current club schedule, as described in the v1 API:
https://github.com/virtuagym/Virtuagym-Public-API/wiki/Club-Events
This API requires the club secret which is of course unknown to members. However each member can easily retrieve the schedule for clubs where they are a member of in the official app so this information is already known to the end user.

Requested feature: An API to retrieve (GET only) the club schedule for clubs where the user is a member of (which is known because the user API returns _employee_club_ids_) without requiring the club secret.

**Comment by sanjay900** [comment]
Try `/api/v0/club/{club}/event/{from}/to/{to}&api_key={api_key}`

Where from is an iso8601 date and to is an iso8601 date, both without times
e.g. `/api/v0/club/00000/event/2022-01-24/to/2022-01-25&api_key=xxxx`

**Comment by gceka25** [comment]
@nick-van-h  Please note, in API endpoints we pass the "Club Key" as "club_secret"

(Club Key can be found in System Settings -> Business Info -> Advanced)
