### ISSUE TITLE
Invoices - Wrong documentation

### ISSUE THREAD

**Issue by xsrsx** [virtuagym/Virtuagym-Public-API#43]
The documentation for invoices is somehow incorrect. 
`
GET | /api/v1/club/<club_id>/invoices/<invoice_id>/ | Returns invoice corresponding to <invoice_id> | api_key, club_secret
`
This either gives an "Invalid API Request" or, if you change to a url like "https://api.virtuagym.com/api/v1/club/.../invoice/invoice?api_key=...club_secret=...&invoice_id",  "Invoice guid not found". 
What is the right request for querying invoices and is there access to all invoices?

**Comment by gceka25** [comment]
@xsrsx The url should be like this:` https://api.virtuagym.com/api/v1/club/<club_id>/invoice/<invoice_id>?api_key=<api_key>&club_secret=<club_secret>`, in your url there is a misplacement of invoice_id value.

**Comment by xsrsx** [comment]
Thank you for the response. Correct link would be:
https://api.virtuagym.com/api/v1/club/<club_id>/invoice**s**/<invoice_id>?api_key=<api_key>&club_secret=<club_secret>
Invoice ID is the GUID and not the No :)
