### ISSUE TITLE
oauth ocid

### ISSUE THREAD

**Issue by aronsuarez** [virtuagym/Virtuagym-Public-API#45]
What are the urls for the oicd configuration?

**Comment by gceka25** [comment]
@aronsuarez https://github.com/virtuagym/Virtuagym-Public-API/wiki/Authorization#facebook-login

**Comment by vgpaulo** [comment]
Hi @aronsuarez , 

Unfortunately, currently we do not support OIDC. Apologies for the delayed answer, for future question, please reach out directly to api@virtuagym.com

Thank you!
