### ISSUE TITLE
token requirement on Public API v0

### ISSUE THREAD

**Issue by JohnMoor** [virtuagym/Virtuagym-Public-API#47]
When trying the API v0 with my credentials basic auth I get a response below. Reading the documentation it is not clear to me how the API expects the API-key to be presented. Any guidance would be appreciated. 

`{
    "statuscode": 401,
    "statusmessage": "Missing or invalid API Key.",
    "result_count": 0,
    "timestamp": 1692219817
}`

**Comment by JohnMoor** [comment]
Never mind, found the solution described in [this issue](https://github.com/virtuagym/Virtuagym-Public-API/issues/42#issuecomment-1019612631):

/api/v0/club/{club}/event/{from}/to/{to}&api_key={api_key}

**Comment by lukasfehling** [comment]
@gaguevaras @salv0 @markh07 it'd be a big help if you could add the info from this comment to the wiki here: https://github.com/virtuagym/Virtuagym-Public-API/issues/42#issuecomment-1303137796, as I ran into the same issue.
