### ISSUE TITLE
Email Issues in your API.

### ISSUE THREAD

**Issue by yogeshpatel2200** [virtuagym/Virtuagym-Public-API#5]
When i update my member status active true to false i got below mail

![image](https://cloud.githubusercontent.com/assets/21233151/21292427/4df9e4fa-c52b-11e6-8c69-c07c0b7a3d19.png)

**Comment by nathan-virtuagym** [comment]
Hi @yogeshpatel2200 ,
Can you please contact support@virtuagym.com regarding this issue so they can cross-check and keep track of it?
