### ISSUE TITLE
Major Bug in Club-Member API

### ISSUE THREAD

**Issue by yogeshpatel2200** [virtuagym/Virtuagym-Public-API#6]
I can create 4 member using same email address, there is no uniqueness of email address, please check below my response.

![image](https://cloud.githubusercontent.com/assets/21233151/21292432/8b40efa2-c52b-11e6-84ae-d347011c91e1.png)

**Comment by nathan-virtuagym** [comment]
Hi @yogeshpatel2200 ,
This is not a bug but rather how the platform itself works - we allow creating multiple members with the same email address.

For instance, take an example where a father and son go to the same gym. In this case, the father would like to get the e-mails that the son's member profile receives to keep track of it (invoices, memberships, etc.).

The uniqueness check occurs in the user profile when someone activates his account but not for the member.

**Comment by yogeshpatel2200** [comment]
So, how can i check user exist or not with same email address, i want to add user based on email address.

**Comment by nathan-virtuagym** [comment]
Hi @yogeshpatel2200,
If you are referring to creating a member with a unique e-mail address, you might have to check for uniqueness on your end, unfortunately we cannot accommodate this check.

But, if you are referring to a user profile (client login with username and password), then the API would reject the call for uniqueness.

A user profile does not directly belong to a club but is linked to it through a member profile.

Currently, the API does not support creating a member profile based on a user profile, please contact support@virtuagym.com if you want such a feature to be built.
