### ISSUE TITLE
When I Update member is_pro 1, but not working?

### ISSUE THREAD

**Issue by yogeshpatel2200** [virtuagym/Virtuagym-Public-API#7]
Hello,

First i 'inactive' my member as well as i set 'is_pro' = false that is working fine, but once i call another api with 'is_pro' = true with 'active' ='true' that time 'is_pro' not updated.

**Comment by nathan-virtuagym** [comment]
Hi @yogeshpatel2200,
When you pass 'is_pro=true` then you must also pass 'pro_start' and 'pro_end'.

More here - https://github.com/virtuagym/Virtuagym-Public-API/wiki/Club-Members#put-example

**Comment by yogeshpatel2200** [comment]
I already pass those both things, it give me success response but member
not become pro in web as well as app.
Please suggest me. Thanks

**Comment by nathan-virtuagym** [comment]
Hi @yogeshpatel2200,
Here is a very simple body

```json
{
"active":true,
 "is_pro": true,
 "pro_start":   1482323669,
 "pro_end":  1483323669
}
```

which would be sent to the following URL 

`https://virtuagym.com/api/v1/club/<club_id>/member/<member_id>?api_key=<api_key>&club_secret=<club_secret>`

and allows to active the member with `<member_id>` and give him a pro membership from 21-12-2016 until 02-01-2017 according to the timestamp in seconds that was passed.

**Comment by yogeshpatel2200** [comment]
Thank for your support.
