### ISSUE TITLE
Retrieve event list

### ISSUE THREAD

**Issue by BlockBlockowski** [virtuagym/Virtuagym-Public-API#9]
Hello,

I'm trying to get my club's event list by using the documentation's given route but I get a 500 code response.
The wiki is globally well done (thumbs up) so I guess I'm missing something.
Here is the url requested : 
`https://virtuagym.com/api/v1/club/<club_id>/events?api_key=<api-key>&club_secret=<club-secret>`

Also, other minor problem, when I'm getting my club's member list, I can't filter the array when I'm sending the param "?is_pro=true". 
`https://virtuagym.com/api/v1/club/<club_id>/member?api_key=<api-key>&club_secret=<club-secret>&is_pro=true`
Is there a way to get my club's professional list ?

Thank you and good job on the API !

**Comment by richarddigifit** [comment]
Hi, 
That's weird. Which club_id are you using?

Unfortunately the is_pro parameter is not supported in the member call. You'll have to filter the results yourself locally.

**Comment by BlockBlockowski** [comment]
My club_id is 15657
By the way, I've found out if I give a random schedule_id param (I've found what is this exactly yet), I can get an empty result. Could that be linked eventually ?

Bad news, but yes I was thinking about filter the result on my own. Just a lot of results for a few professional. Nevermind.

**Comment by richarddigifit** [comment]
There seems to be a bug in our code that causes this. However if you provide a timestamp_start parameter your call seems to work. 

For example 
https://virtuagym.com/api/v1/club/<club_id>/events?api_key=<api-key>&club_secret=<club-secret>&timestamp_start=1483228800

= all events from 1 Jan 2017 to now)

**Comment by BlockBlockowski** [comment]
Yes it works !! 

Thank you. :)
